-- Löschen Sie vorhandene News-Einträge (optional)
DELETE FROM "News" WHERE true;

-- Fügen Sie die Test-Datensätze ein
INSERT INTO "News" (
  "id",
  "title",
  "subtitle",
  "shortText",
  "longText",
  "imageUrl",
  "author",
  "category",
  "tags",
  "publishDate",
  "isPublished",
  "viewCount",
  "readTime",
  "createdAt",
  "updatedAt"
) VALUES
(
  'news-1',
  'Digitale Transformation: Mittelstand investiert Rekordsummen in KI und Automatisierung',
  'Neue Studie zeigt Investitionstrends 2025',
  'Eine neue Studie zeigt: Deutsche Mittelständler investieren 2025 so viel wie nie zuvor in digitale Technologien. Besonders KI-Lösungen und Automatisierungsprozesse stehen im Fokus. Die Investitionen sollen die Wettbewerbsfähigkeit sichern und neue Geschäftsmodelle ermöglichen.',
  '<h2>Studie zur Digitalisierung</h2><p>Die <strong>Digitalisierung</strong> im deutschen Mittelstand schreitet rasant voran. Unternehmen investieren verstärkt in <em>künstliche Intelligenz</em> und <em>Automatisierung</em>, um ihre Wettbewerbsfähigkeit zu sichern. <ul><li>KI-Lösungen werden in der Produktion und Verwaltung eingesetzt.</li><li>Automatisierungsprozesse optimieren die Effizienz.</li></ul> <p>Die Studie hebt hervor, dass besonders kleine und mittlere Unternehmen (KMU) von diesen Investitionen profitieren. <blockquote>"Die Bereitschaft zur Digitalisierung ist so hoch wie nie zuvor."</blockquote></p>',
  '/news-0.jpg',
  'Dr. Maria Schmidt',
  'DIGITALISIERUNG',
  ARRAY['KI', 'Digitalisierung', 'Mittelstand', 'Automatisierung'],
  NOW() - INTERVAL '1 day',
  true,
  156,
  '7 Min.',
  NOW(),
  NOW()
),
(
  'news-2',
  'Neue Förderprogramme für KMU in NRW beschlossen',
  'Millionen-Budget für digitale Innovation',
  'Das Land NRW hat neue Förderprogramme für kleine und mittlere Unternehmen beschlossen. Die Programme zielen darauf ab, die digitale Transformation zu unterstützen und Innovationen zu fördern. Ein Schwerpunkt liegt auf der Unterstützung von Cloud-Computing und Cybersicherheit.',
  '<h2>Förderprogramme 2025</h2><p>Das Land NRW stellt ein Millionen-Budget für die <strong>digitale Innovation</strong> bereit. <ul><li>Förderung von Cloud-Computing</li><li>Unterstützung der Cybersicherheit</li></ul> <p>Unternehmen können sich ab sofort bewerben. Die Programme sind Teil der Digitalstrategie NRW.</p>',
  '/news-1.jpg',
  'Michael Weber',
  'FOERDERUNG',
  ARRAY['Förderung', 'KMU', 'NRW', 'Innovation'],
  NOW() - INTERVAL '2 days',
  true,
  98,
  '5 Min.',
  NOW(),
  NOW()
),
(
  'news-3',
  'Erfolgreiches Business Networking Event mit 200 Teilnehmern',
  'Große Resonanz auf Hamburger Wirtschaftstreffen',
  'Das gestrige Business Networking Event in Hamburg war ein voller Erfolg. Über 200 Unternehmer und Führungskräfte nutzten die Gelegenheit zum Austausch und zur Kontaktpflege. Mehrere vielversprechende Kooperationen wurden bereits vor Ort angebahnt.',
  '<h2>Networking Event Hamburg</h2><p>Das Event brachte über 200 Unternehmer und Führungskräfte zusammen. <ul><li>Intensive Gespräche und neue Kontakte</li><li>Kooperationen wurden angebahnt</li></ul> <p>Die Veranstalter zeigten sich sehr zufrieden mit der Resonanz. <blockquote>"Ein voller Erfolg für die Hamburger Wirtschaft!"</blockquote></p>',
  '/news-2.jpg',
  'Lisa Müller',
  'NETZWERK',
  ARRAY['Networking', 'Hamburg', 'Business', 'Event'],
  NOW() - INTERVAL '3 days',
  true,
  124,
  '6 Min.',
  NOW(),
  NOW()
),
(
  'news-4',
  'Deutsche Exporte erreichen neues Allzeithoch',
  'Positive Entwicklung trotz globaler Herausforderungen',
  'Die deutschen Exporte haben im ersten Halbjahr 2025 einen neuen Rekordwert erreicht. Besonders die Nachfrage nach Industriegütern und High-Tech-Produkten ist stark gestiegen. Experten sehen darin ein positives Signal für die weitere wirtschaftliche Entwicklung.',
  '<h2>Export-Rekord 2025</h2><p>Die deutschen Exporteure profitieren von einer starken Nachfrage. <ul><li>Industriegüter und High-Tech-Produkte besonders gefragt</li><li>Experten sehen positive Entwicklung</li></ul> <p>Die Bundesregierung erwartet weiteres Wachstum im Exportsektor.</p>',
  '/news-3.jpg',
  'Prof. Dr. Thomas Becker',
  'WIRTSCHAFT',
  ARRAY['Export', 'Wirtschaft', 'Handel', 'Wachstum'],
  NOW() - INTERVAL '4 days',
  true,
  187,
  '8 Min.',
  NOW(),
  NOW()
),
(
  'news-5',
  'NRW wird zum Startup-Hub: 15 neue Tech-Unternehmen gegründet',
  'Innovationsstandort NRW wächst weiter',
  'In den letzten Wochen wurden in NRW 15 neue Tech-Startups gegründet. Die Unternehmen sind vor allem in den Bereichen KI, Clean-Tech und Digital Health aktiv. Die lokale Startup-Szene entwickelt sich damit weiter zu einem wichtigen Innovations-Hub in Deutschland.',
  '<h2>Startup-Boom in NRW</h2><p>NRW entwickelt sich zum Hotspot für Tech-Startups. <ul><li>15 neue Unternehmen in den letzten Wochen</li><li>Fokus auf KI, Clean-Tech und Digital Health</li></ul> <p>Die Landesregierung unterstützt die Entwicklung mit gezielten Förderprogrammen.</p>',
  '/news-4.jpg',
  'Sarah Klein',
  'TECHNOLOGIE',
  ARRAY['Startup', 'Tech', 'NRW', 'Innovation'],
  NOW() - INTERVAL '5 days',
  true,
  145,
  '5 Min.',
  NOW(),
  NOW()
);
