-- Löschen Sie vorhandene News-Einträge (optional)
DELETE FROM "News" WHERE true;

-- Fügen Sie die Test-Datensätze ein
INSERT INTO "News" (
  "id",
  "title",
  "subtitle",
  "content",
  "imageUrl",
  "author",
  "category",
  "tags",
  "publishDate",
  "isPublished",
  "viewCount",
  "readTime",
  "createdAt",
  "updatedAt"
) VALUES
(
  'news-1',
  'Digitale Transformation: Mittelstand investiert Rekordsummen in KI und Automatisierung',
  'Neue Studie zeigt Investitionstrends 2025',
  'Eine neue Studie zeigt: Deutsche Mittelständler investieren 2025 so viel wie nie zuvor in digitale Technologien. Besonders KI-Lösungen und Automatisierungsprozesse stehen im Fokus. Die Investitionen sollen die Wettbewerbsfähigkeit sichern und neue Geschäftsmodelle ermöglichen. Die Studie, durchgeführt von renommierten Wirtschaftsforschern, zeigt einen deutlichen Anstieg der Digitalisierungsbereitschaft im Vergleich zu den Vorjahren. Besonders bemerkenswert ist der Fokus auf künstliche Intelligenz und Machine Learning, die als Schlüsseltechnologien der Zukunft identifiziert wurden.',
  '/news-0.jpg',
  'Dr. Maria Schmidt',
  'DIGITALISIERUNG',
  ARRAY['KI', 'Digitalisierung', 'Mittelstand', 'Automatisierung'],
  NOW() - INTERVAL '1 day',
  true,
  156,
  '7 Min.',
  NOW(),
  NOW()
),
(
  'news-2',
  'Neue Förderprogramme für KMU in NRW beschlossen',
  'Millionen-Budget für digitale Innovation',
  'Das Land NRW hat neue Förderprogramme für kleine und mittlere Unternehmen beschlossen. Die Programme zielen darauf ab, die digitale Transformation zu unterstützen und Innovationen zu fördern. Ein Schwerpunkt liegt auf der Unterstützung von Cloud-Computing und cybersicherheit.',
  '/news-1.jpg',
  'Michael Weber',
  'FOERDERUNG',
  ARRAY['Förderung', 'KMU', 'NRW', 'Innovation'],
  NOW() - INTERVAL '2 days',
  true,
  98,
  '5 Min.',
  NOW(),
  NOW()
),
(
  'news-3',
  'Erfolgreiches Business Networking Event mit 200 Teilnehmern',
  'Große Resonanz auf Hamburger Wirtschaftstreffen',
  'Das gestrige Business Networking Event in Hamburg war ein voller Erfolg. Über 200 Unternehmer und Führungskräfte nutzten die Gelegenheit zum Austausch und zur Kontaktpflege. Mehrere vielversprechende Kooperationen wurden bereits vor Ort angebahnt.',
  '/news-2.jpg',
  'Lisa Müller',
  'NETZWERK',
  ARRAY['Networking', 'Hamburg', 'Business', 'Event'],
  NOW() - INTERVAL '3 days',
  true,
  124,
  '6 Min.',
  NOW(),
  NOW()
),
(
  'news-4',
  'Deutsche Exporte erreichen neues Allzeithoch',
  'Positive Entwicklung trotz globaler Herausforderungen',
  'Die deutschen Exporte haben im ersten Halbjahr 2025 einen neuen Rekordwert erreicht. Besonders die Nachfrage nach Industriegütern und High-Tech-Produkten ist stark gestiegen. Experten sehen darin ein positives Signal für die weitere wirtschaftliche Entwicklung.',
  '/news-3.jpg',
  'Prof. Dr. Thomas Becker',
  'WIRTSCHAFT',
  ARRAY['Export', 'Wirtschaft', 'Handel', 'Wachstum'],
  NOW() - INTERVAL '4 days',
  true,
  187,
  '8 Min.',
  NOW(),
  NOW()
),
(
  'news-5',
  'NRW wird zum Startup-Hub: 15 neue Tech-Unternehmen gegründet',
  'Innovationsstandort NRW wächst weiter',
  'In den letzten Wochen wurden in NRW 15 neue Tech-Startups gegründet. Die Unternehmen sind vor allem in den Bereichen KI, Clean-Tech und Digital Health aktiv. Die lokale Startup-Szene entwickelt sich damit weiter zu einem wichtigen Innovations-Hub in Deutschland.',
  '/news-4.jpg',
  'Sarah Klein',
  'TECHNOLOGIE',
  ARRAY['Startup', 'Tech', 'NRW', 'Innovation'],
  NOW() - INTERVAL '5 days',
  true,
  145,
  '5 Min.',
  NOW(),
  NOW()
);
